//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialMovement
    {
        public int id { get; set; }
        public int material_id { get; set; }
        public int type_id { get; set; }
        public decimal quantity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string reason { get; set; }
    
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual MovementType MovementType { get; set; }
    }
}
