//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public decimal good_quantity { get; set; }
        public Nullable<decimal> defect_quantity { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
    
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
