//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStock
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public string batch_number { get; set; }
        public decimal quantity { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
